<?php
return [
  [
    'name' => 'CustomGroup_Education',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Education',
        'title' => 'Education',
        'extends' => 'Contact',
        'extends_entity_column_value' => NULL,
        'style' => 'Tab with table',
        'collapse_display' => FALSE,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 5,
        'is_active' => TRUE,
        'is_multiple' => TRUE,
        'min_multiple' => NULL,
        'max_multiple' => 5,
        'collapse_adv_display' => TRUE,
        'created_date' => '2022-06-07 23:43:11',
        'is_reserved' => FALSE,
        'is_public' => TRUE,
        'icon' => '',
        'extends_entity_column_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Education_CustomField_School',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Education',
        'name' => 'School',
        'label' => 'School',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'school_13',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Education_CustomField_Start_Year',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Education',
        'name' => 'Start_Year',
        'label' => 'Start Year',
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => 60,
        'end_date_years' => 10,
        'date_format' => 'yy',
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'start_year_14',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
];
